ALTER TABLE "User"
ALTER COLUMN "totalPoints" TYPE DOUBLE PRECISION
USING "totalPoints"::DOUBLE PRECISION;

ALTER TABLE "CompetitionEntry"
ALTER COLUMN "totalPoints" TYPE DOUBLE PRECISION
USING "totalPoints"::DOUBLE PRECISION;

ALTER TABLE "Prediction"
ALTER COLUMN "pointsAwarded" TYPE DOUBLE PRECISION
USING "pointsAwarded"::DOUBLE PRECISION;

ALTER TABLE "LeaderboardSnapshot"
ALTER COLUMN "totalPoints" TYPE DOUBLE PRECISION
USING "totalPoints"::DOUBLE PRECISION;

ALTER TABLE "TournamentWinner"
ALTER COLUMN "finalPoints" TYPE DOUBLE PRECISION
USING "finalPoints"::DOUBLE PRECISION;
